### ISSUE TITLE
Upgrade jupytext

### ISSUE THREAD

**Issue by rsokl** [alexding123/Learning_Python#5]
Hi Alex,

`jupytext` has been making some substantial updates, and I've written some simple utilities for upgrading the PLYMI source material. 

My repo now has an installable python package called `plymi`. Once you install it, you can simply upgrade to `jupytext==1.3.0rc2` (or just wait until `1.3.0` actually comes out) and run:

```python
import plymi
from pathlib import Path
root = Path("./Learning_Python/").absolute()
plymi.convert_all_markdown_to_markdown(root)
```

Assuming that you are using the same directory / notebook names as me, this will upgrade all of your notebooks.

**Comment by alexding123** [comment]
Hey Ryan,

Thank you so much for the update! For some reason, I'm not getting any notification for all the issues you're creating in this repo. I'll start addressing them this weekend!
